#+STARTUP: overview
#+STARTUP: hidestars
#+TODO: TODO(t!) FOCUSED (f@/!) STARTED(s@/!) WAITING(w@/!) SOMEDAY(S@/!) URGENT (u!) | DONE(d!) CANCELED(c@!)
#+PRIORITIES: A C B
* Template for software developpment with AT91SAM9G20-EK based on ISIS I-OBC libraries
** DONE Blink test using ISIS libraries
   - State "DONE"       from "TODO"       [2019-02-16 Sat 18:55]
*** DONE Specification
    - State "DONE"       from "TODO"       [2018-06-11 Mon 17:09]
**** Abstract
     Our goal is to make a led blink with the AT91SAM9G20-EK board using
     FreeRTOS and ISIS static libraries.
     
     In order to achieve this we need to compile ISIS'port of FreeRTOS
     realtime operating system and other libraries, write a blinky
     program, compile it, flash it and verify our software.

     Our standard programming language is the C programming language
     with the C99 standard.
**** DONE Linking FreeRTOs  Linking FreeRTOS and static libraries
     - State "DONE"       from "TODO"       [2018-06-11 Mon 16:59]
   
     The FreeRTOS real time operating system is widely used and
     documentation on it is extensive. FreeRTOS is not entirely
     architecture indepent this is why we need a port for some
     specific files to work with our particular μ-controller.
     
     Fortunately FreeRTOS has been ported to work with our target
     microcontroller by ISIS.
     
*** DONE Test
    - State "DONE"       from "TODO"       [2019-02-16 Sat 18:55]
**** DONE Linking FreeRTOS and static libraries

     - State "DONE"       from "TODO"       [2019-02-16 Sat 18:55]
     Thourough tests have been carried out by ISIS, we need only to
     make a functional test of FreeRTOS tasks.
     
*** DONE Programming
    - State "DONE"       from "TODO"       [2018-06-11 Mon 17:08]
**** DONE Linking FreeRTOS and static libraries
     - State "DONE"       from "TODO"       [2018-06-11 Mon 17:08]
     We will base ourselfs on the ISIS FirstProject that to be used as
     a template for new projects and rewrite the program.
     
* Notes
  You shall note that AT91LIB distributed by ISIS has been used. The
  startup file has been patched to load FreeRTOS callbacks on
  exception handlers in src/boot_fstartup.S .
  
  As well, to improve portability some scripts where re-written in
  bash i.e. debug.pl.
  
  The following makefile targets : jlink, flashing, connect are only
  for convenience and call scripts for, respectively, start a j-link
  communication, flashing the board and connecting to the debug
  port. These scripts use third party software and should be adapted
  according to your usage an set-up. They are included only for
  convenience.

  In order to run the program you can connect through j-link, run the
  jlink server and type make debug_sdram and type continue on through
  GDB.
